export const FETCH_ENTITY_BY_ID_REQUEST = 'FETCH_ENTITY_BY_ID__REQUEST';
export const FETCH_ENTITY_BY_ID_SUCCESS = 'FETCH_ENTITY_BY_ID_SUCCESS';
export const FETCH_ENTITY_BY_ID_FAILURE = 'FETCH_ENTITY_BY_ID_FAILURE';
