export const FETCH_GROUP_BY_ID_REQUEST = 'FETCH_GROUP_BY_ID_REQUEST';
export const FETCH_GROUP_BY_ID_SUCCESS = 'FETCH_GROUP_BY_ID_SUCCESS';
export const FETCH_GROUP_BY_ID_FAILURE = 'FETCH_GROUP_BY_ID_FAILURE';
