export const FETCH_GROUPS_BY_IDS_REQUEST = 'FETCH_GROUPS_BY_IDS_REQUEST';
export const FETCH_GROUPS_BY_IDS_SUCCESS = 'FETCH_GROUPS_BY_IDS_SUCCESS';
export const FETCH_GROUPS_BY_IDS_FAILURE = 'FETCH_GROUPS_BY_IDS_FAILURE';
